import { useState } from 'react'
import { ArrowLeft, CheckCircle, Mail, SendHorizontal } from 'lucide-react'

export default function ChatPage({ message, onBack }) {
  const [showSummary, setShowSummary] = useState(false)
  const telegram = message.canal === 'Telegram'
  return <div className="chat-view mx-auto my-4 flex h-[min(720px,calc(100vh-180px))] min-h-[480px] max-w-4xl flex-col overflow-hidden rounded-lg border border-gray-200 bg-gray-100 shadow-md">
    <div className={`flex items-center justify-between gap-3 px-4 py-3 text-white shadow-sm sm:px-6 ${telegram ? 'bg-[#0088cc]' : 'bg-[#EA4335]'}`}><div className="flex min-w-0 items-center gap-3"><button onClick={onBack} className="rounded-sm p-1 hover:bg-white/15" aria-label="Volver"><ArrowLeft size={22} /></button><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full border border-white/10 bg-white/20 font-bold uppercase">{message.nombre.split(' ').map((part) => part[0]).join('')}</div><div className="min-w-0"><h2 className="truncate text-base font-semibold leading-tight">{message.nombre}</h2><span className="text-xs opacity-75">Historial multicanal · {message.address}</span></div></div><button disabled title="No disponible en la demo" className="hidden cursor-not-allowed items-center gap-2 rounded-md border border-white/30 bg-emerald-600 px-3 py-1.5 text-sm font-medium opacity-50 sm:flex"><CheckCircle size={16} /> Finalizar y enviar encuesta</button></div>
    <div className="chat-pattern flex-1 overflow-y-auto p-4 sm:p-6"><div className="flex max-w-[85%] flex-col items-start sm:max-w-[75%]"><button onClick={() => setShowSummary((value) => !value)} className={`w-full rounded-xl rounded-tl-none border-l-4 bg-white p-3.5 text-left shadow-sm ${telegram ? 'border-l-[#32afed]' : 'border-l-[#EA4335]'} ${showSummary ? 'ring-2 ring-primary' : ''}`} aria-expanded={showSummary}><span className={`mb-2 inline-flex items-center gap-1 rounded-full px-2 py-0.5 text-[10px] font-bold uppercase text-white ${telegram ? 'bg-[#32afed]' : 'bg-[#EA4335]'}`}>{telegram ? <SendHorizontal size={11} /> : <Mail size={11} />}{message.canal}</span><span className="block whitespace-pre-wrap break-words text-sm leading-relaxed text-gray-900">{message.contenido}</span><span className="mt-1 block text-right text-[10px] text-gray-500">{new Date(message.fecha).toLocaleString('es-UY')}</span></button>{showSummary && <div className="ml-2 mt-2 rounded border border-blue-200 bg-blue-50/95 p-2 text-xs text-blue-900"><strong className="mb-1 block text-blue-700">Resumen de ejemplo</strong>{message.resumen}</div>}</div>
      <div className="ml-auto mt-6 max-w-[85%] rounded-xl rounded-tr-none border border-[#a3e49b] bg-[#D9FDD3] p-3.5 text-gray-900 shadow-sm sm:max-w-[75%]"><div className="mb-1 flex items-center justify-between gap-5 text-[10px] font-bold text-emerald-700"><span>Agente demo</span><span className="uppercase text-gray-500">Vía {message.canal}</span></div><p className="text-sm leading-relaxed">Gracias por escribirnos. Estamos revisando tu consulta y te responderemos con más información.</p><p className="mt-1 text-right text-[10px] text-gray-500">Respuesta ficticia</p></div></div>
    <div className="flex items-center gap-3 border-t border-gray-200 bg-[#f0f2f5] p-4"><span className="w-32 shrink-0 rounded-lg border border-gray-300 bg-gray-100 px-3 py-2.5 text-xs text-gray-500">{message.canal}</span><input disabled value="Envío no disponible en esta demo" aria-label="Respuesta deshabilitada" className="h-10 min-w-0 flex-1 cursor-not-allowed rounded-lg border border-gray-300 bg-gray-200 px-4 text-sm text-gray-500" readOnly /><button disabled aria-label="Enviar deshabilitado" title="Envío no disponible en esta demo" className="flex h-10 w-10 shrink-0 cursor-not-allowed items-center justify-center rounded-lg bg-gray-400 text-white"><SendHorizontal size={17} /></button></div>
  </div>
}
